let languageObj = {
  languages: [
    { text: "Afar", code: "aa" },
    { text: "Abkhazian", code: "ab" },
    { text: "Avestan", code: "ae" },
    { text: "Afrikaans", code: "af" },
    { text: "Akan", code: "ak" },
    { text: "Amharic", code: "am" },
    { text: "Aragonese", code: "an" },
    { text: "Arabic", code: "ar" },
    { text: "Assamese", code: "as" },
    { text: "Avaric", code: "av" },
    { text: "Aymara", code: "ay" },
    { text: "Azerbaijani", code: "az" },
    { text: "Bashkir", code: "ba" },
    { text: "Belarusian", code: "be" },
    { text: "Bulgarian", code: "bg" },
    { text: "Bihari languages", code: "bh" },
    { text: "Bislama", code: "bi" },
    { text: "Bambara", code: "bm" },
    { text: "Bengali", code: "bn" },
    { text: "Tibetan", code: "bo" },
    { text: "Breton", code: "br" },
    { text: "Bosnian", code: "bs" },
    { text: "Catalan; Valencian", code: "ca" },
    { text: "Chechen", code: "ce" },
    { text: "Chamorro", code: "ch" },
    { text: "Corsican", code: "co" },
    { text: "Cree", code: "cr" },
    { text: "Czech", code: "cs" },
    { text: "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", code: "cu" },
    { text: "Chuvash", code: "cv" },
    { text: "Welsh", code: "cy" },
    { text: "Danish", code: "da" },
    { text: "German", code: "de" },
    { text: "Divehi; Dhivehi; Maldivian", code: "dv" },
    { text: "Dzongkha", code: "dz" },
    { text: "Ewe", code: "ee" },
    { text: "Greek, Modern (1453-)", code: "el" },
    { text: "English", code: "en" },
    { text: "Esperanto", code: "eo" },
    { text: "Spanish; Castilian", code: "es" },
    { text: "Estonian", code: "et" },
    { text: "Basque", code: "eu" },
    { text: "Persian", code: "fa" },
    { text: "Fulah", code: "ff" },
    { text: "Finnish", code: "fi" },
    { text: "Fijian", code: "fj" },
    { text: "Faroese", code: "fo" },
    { text: "French", code: "fr" },
    { text: "Western Frisian", code: "fy" },
    { text: "Irish", code: "ga" },
    { text: "Gaelic; Scottish Gaelic", code: "gd" },
    { text: "Galician", code: "gl" },
    { text: "Guarani", code: "gn" },
    { text: "Gujarati", code: "gu" },
    { text: "Manx", code: "gv" },
    { text: "Hausa", code: "ha" },
    { text: "Hebrew", code: "he" },
    { text: "Hindi", code: "hi" },
    { text: "Hiri Motu", code: "ho" },
    { text: "Croatian", code: "hr" },
    { text: "Haitian; Haitian Creole", code: "ht" },
    { text: "Hungarian", code: "hu" },
    { text: "Armenian", code: "hy" },
    { text: "Herero", code: "hz" },
    { text: "Interlingua (International Auxiliary Language Association)", code: "ia" },
    { text: "Indonesian", code: "id" },
    { text: "Interlingue; Occidental", code: "ie" },
    { text: "Igbo", code: "ig" },
    { text: "Sichuan Yi; Nuosu", code: "ii" },
    { text: "Inupiaq", code: "ik" },
    { text: "Ido", code: "io" },
    { text: "Icelandic", code: "is" },
    { text: "Italian", code: "it" },
    { text: "Inuktitut", code: "iu" },
    { text: "Japanese", code: "ja" },
    { text: "Javanese", code: "jv" },
    { text: "Georgian", code: "ka" },
    { text: "Kongo", code: "kg" },
    { text: "Kikuyu; Gikuyu", code: "ki" },
    { text: "Kuanyama; Kwanyama", code: "kj" },
    { text: "Kazakh", code: "kk" },
    { text: "Kalaallisut; Greenlandic", code: "kl" },
    { text: "Central Khmer", code: "km" },
    { text: "Kannada", code: "kn" },
    { text: "Korean", code: "ko" },
    { text: "Kanuri", code: "kr" },
    { text: "Kashmiri", code: "ks" },
    { text: "Kurdish", code: "ku" },
    { text: "Komi", code: "kv" },
    { text: "Cornish", code: "kw" },
    { text: "Kirghiz; Kyrgyz", code: "ky" },
    { text: "Latin", code: "la" },
    { text: "Luxembourgish; Letzeburgesch", code: "lb" },
    { text: "Ganda", code: "lg" },
    { text: "Limburgan; Limburger; Limburgish", code: "li" },
    { text: "Lingala", code: "ln" },
    { text: "Lao", code: "lo" },
    { text: "Lithuanian", code: "lt" },
    { text: "Luba-Katanga", code: "lu" },
    { text: "Latvian", code: "lv" },
    { text: "Malagasy", code: "mg" },
    { text: "Marshallese", code: "mh" },
    { text: "Maori", code: "mi" },
    { text: "Macedonian", code: "mk" },
    { text: "Malayalam", code: "ml" },
    { text: "Mongolian", code: "mn" },
    { text: "Marathi", code: "mr" },
    { text: "Malay", code: "ms" },
    { text: "Maltese", code: "mt" },
    { text: "Burmese", code: "my" },
    { text: "Nauru", code: "na" },
    { text: "Bokmål, Norwegian; Norwegian Bokmål", code: "nb" },
    { text: "Ndebele, North; North Ndebele", code: "nd" },
    { text: "Nepali", code: "ne" },
    { text: "Ndonga", code: "ng" },
    { text: "Dutch; Flemish", code: "nl" },
    { text: "Norwegian Nynorsk; Nynorsk, Norwegian", code: "nn" },
    { text: "Norwegian", code: "no" },
    { text: "Ndebele, South; South Ndebele", code: "nr" },
    { text: "Navajo; Navaho", code: "nv" },
    { text: "Chichewa; Chewa; Nyanja", code: "ny" },
    { text: "Occitan (post 1500)", code: "oc" },
    { text: "Ojibwa", code: "oj" },
    { text: "Oromo", code: "om" },
    { text: "Oriya", code: "or" },
    { text: "Ossetian; Ossetic", code: "os" },
    { text: "Panjabi; Punjabi", code: "pa" },
    { text: "Pali", code: "pi" },
    { text: "Polish", code: "pl" },
    { text: "Pushto; Pashto", code: "ps" },
    { text: "Portuguese", code: "pt" },
    { text: "Quechua", code: "qu" },
    { text: "Romansh", code: "rm" },
    { text: "Rundi", code: "rn" },
    { text: "Romanian; Moldavian; Moldovan", code: "ro" },
    { text: "Russian", code: "ru" },
    { text: "Kinyarwanda", code: "rw" },
    { text: "Sanskrit", code: "sa" },
    { text: "Sardinian", code: "sc" },
    { text: "Sindhi", code: "sd" },
    { text: "Northern Sami", code: "se" },
    { text: "Sango", code: "sg" },
    { text: "Sinhala; Sinhalese", code: "si" },
    { text: "Slovak", code: "sk" },
    { text: "Slovenian", code: "sl" },
    { text: "Samoan", code: "sm" },
    { text: "Shona", code: "sn" },
    { text: "Somali", code: "so" },
    { text: "Albanian", code: "sq" },
    { text: "Serbian", code: "sr" },
    { text: "Swati", code: "ss" },
    { text: "Sotho, Southern", code: "st" },
    { text: "Sundanese", code: "su" },
    { text: "Swedish", code: "sv" },
    { text: "Swahili", code: "sw" },
    { text: "Tamil", code: "ta" },
    { text: "Telugu", code: "te" },
    { text: "Tajik", code: "tg" },
    { text: "Thai", code: "th" },
    { text: "Tigrinya", code: "ti" },
    { text: "Turkmen", code: "tk" },
    { text: "Tagalog", code: "tl" },
    { text: "Tswana", code: "tn" },
    { text: "Tonga (Tonga Islands)", code: "to" },
    { text: "Turkish", code: "tr" },
    { text: "Tsonga", code: "ts" },
    { text: "Tatar", code: "tt" },
    { text: "Twi", code: "tw" },
    { text: "Tahitian", code: "ty" },
    { text: "Uighur; Uyghur", code: "ug" },
    { text: "Ukrainian", code: "uk" },
    { text: "Urdu", code: "ur" },
    { text: "Uzbek", code: "uz" },
    { text: "Venda", code: "ve" },
    { text: "Vietnamese", code: "vi" },
    { text: "Volapük", code: "vo" },
    { text: "Walloon", code: "wa" },
    { text: "Wolof", code: "wo" },
    { text: "Xhosa", code: "xh" },
    { text: "Yiddish", code: "yi" },
    { text: "Yoruba", code: "yo" },
    { text: "Zhuang; Chuang", code: "za" },
    { text: "Chinese", code: "zh" },
    { text: "Zulu", code: "zu" },
  ],
};
module.exports = languageObj;